apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- auth-service.yaml
- api-gateway.yaml
- customer-service.yaml
- account-service.yaml
- ledger-service.yaml
- notification-service.yaml
- audit-fraud-service.yaml
- card-service.yaml
- transaction-service.yaml
- beneficiary-service.yaml
- loan-service.yaml
- frontend.yaml
- ingress.yaml
